### ISSUE TITLE
Logger features

### ISSUE THREAD

**Issue by szgergo** [szgergo/openNas#2]
- [x] Lehetőség a teljes log állományt letölteni (tar.gz-ben)
- [x] Lehetőség kilistázni a log fájlokat (a szokásos adatokkal együtt).
- [x] Törölni log fájlt
- [x] Log fájlok archíválása (tar.gz-ben)
- [x] Automatikus archíválás egy bizonyos időközönként, vagy méret felett
- [x] Közös konfig fájl
- [x] Szerkeszthető log fájl név

**Comment by Sch-Tomi** [comment]
Apró észrevételek:
- Log fájlok archíválása tar.gz-ben, a konfigban már volt zip meg minden, akkor csak targz vagy más is? Teljes lognál is fent áll a kérdés.
- Automatikus Archiválásnál hova mentsen?
- szerkeszthető log fájlnév: abs / rel path kapok? abs jobb lenne akkor bárhova rakhatja az user

**Comment by szgergo** [comment]
1, mindegy melyik, akár választható is lehet, ha ez túl sok meló, akkor amelyik hatékonyabb. 
2, a konfig fájlba legyen egy rekord hozzá ( kérlek egészítsd ki)
3, akkor legyen abs :)

**Comment by Sch-Tomi** [comment]
Everything is Awesome
