### ISSUE TITLE
Config file checker

### ISSUE THREAD

**Issue by szgergo** [szgergo/openNas#3]
Konfig fájlokat induláskor vizsgáló program, egy fájlból veszi majd a lehetséges helyes kulcsokat, és azok lehetséges helyes értékeit.

**Comment by Sch-Tomi** [comment]
![Nothing is True, Everything is Permitted](https://49.media.tumblr.com/tumblr_lxnndz25tC1r2yjgro1_500.gif)

**Comment by szgergo** [comment]
Kész
